package com.huangshangi.novelreader.dao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huangshangi.novelreader.bean.SearchHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_HISTORY".
*/
public class SearchHistoryDao extends AbstractDao<SearchHistory, String> {

    public static final String TABLENAME = "SEARCH_HISTORY";

    /**
     * Properties of entity SearchHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SearchContent = new Property(0, String.class, "searchContent", true, "SEARCH_CONTENT");
        public final static Property SearchTime = new Property(1, String.class, "searchTime", false, "SEARCH_TIME");
    }


    public SearchHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public SearchHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_HISTORY\" (" + //
                "\"SEARCH_CONTENT\" TEXT PRIMARY KEY NOT NULL ," + // 0: searchContent
                "\"SEARCH_TIME\" TEXT);"); // 1: searchTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchHistory entity) {
        stmt.clearBindings();
 
        String searchContent = entity.getSearchContent();
        if (searchContent != null) {
            stmt.bindString(1, searchContent);
        }
 
        String searchTime = entity.getSearchTime();
        if (searchTime != null) {
            stmt.bindString(2, searchTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchHistory entity) {
        stmt.clearBindings();
 
        String searchContent = entity.getSearchContent();
        if (searchContent != null) {
            stmt.bindString(1, searchContent);
        }
 
        String searchTime = entity.getSearchTime();
        if (searchTime != null) {
            stmt.bindString(2, searchTime);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public SearchHistory readEntity(Cursor cursor, int offset) {
        SearchHistory entity = new SearchHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // searchContent
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // searchTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchHistory entity, int offset) {
        entity.setSearchContent(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSearchTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(SearchHistory entity, long rowId) {
        return entity.getSearchContent();
    }
    
    @Override
    public String getKey(SearchHistory entity) {
        if(entity != null) {
            return entity.getSearchContent();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchHistory entity) {
        return entity.getSearchContent() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
